quecon: support subcommand "archive"

diff --git a/quecon b/quecon
--- a/quecon
+++ b/quecon
@@ -180,6 +180,79 @@ function quecon/system:direct/emitdef {
 }
 
 #-----------------------------------------------------------------------------
+# stat
+
+function quecon/jobdir-eval {
+  if [[ ! $1 || ${1//[0-9]} ]]; then
+    echo "quecon: invalid job_index '$1'." >&2
+    return 1
+  fi
+
+  local index=$((10#$1)) command=$2
+  local jobdir i=0
+  for jobdir in "$quecon_data_path"/jobs/????????-??????-*; do
+    [[ -d $jobdir ]] || continue
+    if ((++i==index)); then
+      (cd "$jobdir"; eval -- "$command")
+      return
+    fi
+  done
+  echo "quecon: job_index '$1' not found." >&2
+  return 1
+}
+
+## @param[in] jobdir flags
+## @var[out] line stat
+function quecon/get-job-info {
+  local jobdir=$1 flags=$2
+  [[ -d $jobdir ]] || return 1
+  line= stat=-
+  ((index++))
+  local job_id=${jobdir##*/}
+  local fail=0 done=0 ntask=1
+  local command=- cwd=- node=- time_start= time_end= system=
+
+  local stat_sh
+  for stat_sh in "$jobdir"/stat.sh "$jobdir"/stat?*.sh; do
+    [[ -s $stat_sh ]] || continue
+    source "$stat_sh"
+  done
+  [[ $stat == - && -s $jobdir/complete.mark ]] && stat=C
+
+  local sgr_stat=
+  if ((fail)); then
+    [[ $stat == C* ]] && stat=F$fail
+    [[ $stat == R ]] &&
+      stat=R$done'!'$fail/$ntask
+    sgr_stat=$'\e[1;91m'
+  else
+    case $stat in
+    (F*) sgr_stat=$'\e[1;91m' ;;
+    (C*) [[ $stat == C ]] && stat=COMP
+         sgr_stat=$'\e[94m' ;;
+    (R*) [[ $stat == R ]] &&
+           stat=R$((1+done))/$ntask
+         sgr_stat=$'\e[1;92m' ;;
+    (P*) [[ $stat == P ]] && stat=PEND
+         sgr_stat=$'\e[32m' ;;
+    esac
+  fi
+
+  local time=-
+  if [[ $time_start ]]; then
+    [[ $time_end ]] || time_end=$(date +%s)
+    local ret; quecon/string#seconds-to-human $((time_end-time_start)); time=$ret
+  fi
+
+  printf -v line \
+         '%04d %-18s %-10.10s %s%-6s%s %-6s %s' \
+         "$index" "$job_id" "$node" \
+         "$sgr_stat" "$stat" $'\e[m' \
+         "$time" "$command"
+}
+
+#-----------------------------------------------------------------------------
+# submit
 
 ## @fn cmd:submit/make-jobdir
 ##   @var[out] jobdir
@@ -403,78 +476,6 @@ function cmd:submit {
   done
 }
 
-## @fn cmd:stat/list
-##   @var[in] flags
-function cmd:stat/list {
-  echo 'INDE JOB_ID             NODE       STAT   COMMAND'
-
-  local jobdir index=0
-  for jobdir in "$quecon_data_path"/jobs/????????-??????-*; do
-    [[ -d $jobdir ]] || continue
-    ((index++))
-    local job_id=${jobdir##*/}
-    local stat=- fail=0 done=0 ntask=1
-    local command=- cwd=- node=- time_start= time_end=
-
-    local stat_sh
-    for stat_sh in "$jobdir"/stat.sh "$jobdir"/stat?*.sh; do
-      [[ -s $stat_sh ]] || continue
-      source "$stat_sh"
-    done
-    [[ $stat == - && -s $jobdir/complete.mark ]] && stat=C
-
-    local sgr_stat=
-    if ((fail)); then
-      [[ $stat == C* ]] && stat=F$fail
-      [[ $stat == R ]] &&
-        stat=R$done'!'$fail/$ntask
-      sgr_stat=$'\e[1;91m'
-    else
-      case $stat in
-      (F*) sgr_stat=$'\e[1;91m' ;;
-      (C*) [[ $stat == C ]] && stat=COMP
-           sgr_stat=$'\e[94m' ;;
-      (R*) [[ $stat == R ]] &&
-             stat=R$((1+done))/$ntask
-           sgr_stat=$'\e[1;92m' ;;
-      (P*) [[ $stat == P ]] && stat=PEND
-           sgr_stat=$'\e[32m' ;;
-      esac
-    fi
-    [[ $flags != *a* && $stat == C* ]] && continue
-
-    local time=-
-    if [[ $time_start ]]; then
-      [[ $time_end ]] || time_end=$(date +%s)
-      local ret; quecon/string#seconds-to-human $((time_end-time_start)); time=$ret
-    fi
-
-    printf '%04d %-18s %-10.10s %s%-6s%s %-6s %s\n' \
-           "$index" "$job_id" "$node" \
-           "$sgr_stat" "$stat" $'\e[m' \
-           "$time" "$command"
-  done
-}
-
-function quecon/jobdir-eval {
-  if [[ ! $1 || ${1//[0-9]} ]]; then
-    echo "quecon: invalid job_index '$1'." >&2
-    return 1
-  fi
-
-  local index=$((10#$1)) command=$2
-  local jobdir i=0
-  for jobdir in "$quecon_data_path"/jobs/????????-??????-*; do
-    [[ -d $jobdir ]] || continue
-    if ((++i==index)); then
-      (cd "$jobdir"; eval -- "$command")
-      return
-    fi
-  done
-  echo "quecon: job_index '$1' not found." >&2
-  return 1
-}
-
 quecon/readargs/define-flag-option stat a:all   a
 quecon/readargs/define-flag-option stat help    H
 quecon/readargs/define-flag-option stat version V
@@ -498,6 +499,21 @@ function quecon/readargs:stat/process-argument {
     return 1
   fi
 }
+
+## @fn cmd:stat/list
+##   @var[in] flags
+function cmd:stat/list {
+  echo 'INDE JOB_ID             NODE       STAT   COMMAND'
+
+  local jobdir index=0
+  for jobdir in "$quecon_data_path"/jobs/????????-??????-*; do
+    local line stat
+    quecon/get-job-info "$jobdir" || continue
+    [[ $flags != *a* && $stat == C* ]] && continue
+    printf '%s\n' "$line"
+  done
+}
+
 function cmd:stat/print-version {
   printf 'quecon (idt) 1.0.0\n'
 }
@@ -578,22 +594,38 @@ function cmd:stat {
     return 2 ;;
   esac
 }
-function cmd:compress {
-  local jobdir=$quecon_data_path/jobs
-  (
-    cd "$jobdir"
-    local -a dirs
-    dirs=(2???????-??????-??)
-    ((${#dirs[@]})) || return 0
-    local date=$(date +%Y%m%d)
-    cmd:stat -a >> "$date.stat"
 
-    local arcdir=$date-archive
-    mkd "$arcdir"
-    mv "${dirs[@]}" "$arcdir"
-    cmd:submit "tar cavf $arcdir.tar.xz $arcdir"
-  )
+function cmd:archive {
+  # determine date
+  local jdir=$quecon_data_path/jobs
+  local date=$(date +'%Y%m%d') index=0
+  while [[ -s $jdir/$date.stat ]]; do
+    date=${date%-*}-$((++index))
+  done
+
+  local archive=$jdir/$date-archive.tar.xz
+  local tmpdir=$jdir/$date-archive
+  local statfile=$jdir/$date.stat
+  mkd "$tmpdir"
+
+  local jobdir index=0
+  for jobdir in "$jdir"/2???????-??????-??; do
+    local line stat
+    quecon/get-job-info "$jobdir" || continue
+    [[ $stat == [CF]* ]] || continue
+    printf '%s\n' "$line" >> "$statfile"
+    mv "$jobdir" "$tmpdir"
+  done
+  if [[ -s $statfile ]]; then
+    (cd "$jdir"; tar cavf "${archive##*/}" "${tmpdir##*/}") &&
+      mkd "$jdir/gomi" &&
+      mv "$tmpdir" "$jdir/gomi/"
+  else
+    rmdir "$tmpdir"
+  fi
 }
+
+#------------------------------------------------------------------------------
 
 function main {
   if (($#==0)) || [[ $1 == -* ]]; then
